### ISSUE TITLE
Is pbtools thread safe?

### ISSUE THREAD

**Issue by alexpacini** [eerimoq/pbtools#6]
I was wondering if pbtools can be considered thread safe with its functions re-entrant.

For example, let's say this is used in an embedded system with RTOS and two UART peripheral communicating independently. Each one is handled by its own rx/tx threads and those are encoding/decoding protobuf messages.
Is there any reason why those functions might be non re-entrant? Should the encoding and decoding be protected by some kind of lock for mutual exclusion to avoid concurrency issues?
 
I know it is possible to look at the code, but it is always better to have a comment by the author of the library.

Thanks, Alex.

**Comment by eerimoq** [comment]
It is thread safe.

**Comment by alexpacini** [comment]
Thanks for confirming.

**Comment by nitheeshas** [comment]
@eerimoq Sorry to crack open this old thread.

Since being thread safe and being reentrant are slightly different, do we know if pbtools is reentrant? For example if an ongoing de-/encoding task gets interrupted by a signal handler for a higher priority protobuf de-/encoding.

I've been digging around the source to confirm this but, I guess the same goes as @alexpacini mentioned that it's always good to have a confirmation from the author.

Thanks!

**Comment by eerimoq** [comment]
As long as you don't use the same workspace it is safe. Always have one (or more) workspaces per thread or similar.

**Comment by nitheeshas** [comment]
Perfect, thank you!
